#!/usr/bin/env python3

__author__ = 'Frederic Escudie'
__copyright__ = 'Copyright (C) 2020 IUCT-O'
__license__ = 'GNU General Public License'
__version__ = '1.0.0'
__email__ = 'escudie.frederic@iuct-oncopole.fr'
__status__ = 'prod'

import os
import sys
import unittest

TEST_DIR = os.path.dirname(os.path.abspath(__file__))
PACKAGE_DIR = os.path.dirname(TEST_DIR)
sys.path.append(PACKAGE_DIR)

from anacore.hgvs import HGVSProtChange


########################################################################
#
# FUNCTIONS
#
########################################################################
class TestHGVSProtChange(unittest.TestCase):
    def testParse(self):
        expected = HGVSProtChange("Ter", 757, None, None, None, None, ["Leu"], False)
        observed = HGVSProtChange.fromStr("*757L")
        self.assertEqual(observed, expected)
        observed = HGVSProtChange.fromStr("*757Leu")
        self.assertEqual(observed, expected)
        expected = HGVSProtChange("Val", 600, None, None, None, None, ["="], False)
        observed = HGVSProtChange.fromStr("V600=")
        self.assertEqual(observed, expected)
        observed = HGVSProtChange.fromStr("Val600=")
        self.assertEqual(observed, expected)
        expected = HGVSProtChange("Val", 600, None, None, None, None, ["Glu"], False)
        observed = HGVSProtChange.fromStr("V600E")
        self.assertEqual(observed, expected)
        observed = HGVSProtChange.fromStr("Val600Glu")
        self.assertEqual(observed, expected)
        expected = HGVSProtChange("Val", 600, None, None, None, None, ["Ter"], False)
        observed = HGVSProtChange.fromStr("V600*")
        self.assertEqual(observed, expected)
        observed = HGVSProtChange.fromStr("Val600Ter")
        self.assertEqual(observed, expected)
        expected = HGVSProtChange("Val", 600, None, None, None, "del", [], False)
        observed = HGVSProtChange.fromStr("V600del")
        self.assertEqual(observed, expected)
        observed = HGVSProtChange.fromStr("Val600del")
        self.assertEqual(observed, expected)
        expected = HGVSProtChange("Val", 600, "Ala", 603, None, "del", [], False)
        observed = HGVSProtChange.fromStr("V600_A603del")
        self.assertEqual(observed, expected)
        observed = HGVSProtChange.fromStr("Val600_Ala603del")
        self.assertEqual(observed, expected)
        expected = HGVSProtChange("Val", 600, "Ala", 603, None, "dup", [], False)
        observed = HGVSProtChange.fromStr("V600_A603dup")
        self.assertEqual(observed, expected)
        observed = HGVSProtChange.fromStr("Val600_Ala603dup")
        self.assertEqual(observed, expected)
        expected = HGVSProtChange("Val", 600, "Val", 601, None, "ins", ["(15)"], False)
        observed = HGVSProtChange.fromStr("Val600_Val601ins(15)")
        self.assertEqual(observed, expected)
        expected = HGVSProtChange("Val", 600, "Val", 601, None, "ins", ["15"], False)
        observed = HGVSProtChange.fromStr("Val600_Val601ins15")
        self.assertEqual(observed, expected)
        expected = HGVSProtChange("Cys", 28, None, None, None, "delins", ["Trp", "Val"], False)
        observed = HGVSProtChange.fromStr("C28delinsWV")
        self.assertEqual(observed, expected)
        observed = HGVSProtChange.fromStr("Cys28delinsTrpVal")
        self.assertEqual(observed, expected)
        expected = HGVSProtChange("Cys", 28, "Lys", 29, None, "delins", ["Trp", "Val", "Ter"], False)
        observed = HGVSProtChange.fromStr("C28_K29delinsWV*")
        self.assertEqual(observed, expected)
        observed = HGVSProtChange.fromStr("Cys28_Lys29delinsTrpValTer")
        self.assertEqual(observed, expected)
        # Special cases
        expected = HGVSProtChange(None, None, None, None, None, None, None, False)
        observed = HGVSProtChange.fromStr("?")  # Unknown
        self.assertEqual(observed, expected)
        expected = HGVSProtChange(None, "0", None, None, None, None, None, False)
        observed = HGVSProtChange.fromStr("0")  # No protein
        self.assertEqual(observed, expected)
        # Substitution
        expected = HGVSProtChange("Trp", 24, None, None, None, None, ["Cys"], False)
        observed = HGVSProtChange.fromStr("W24C")  # Missense
        self.assertEqual(observed, expected)
        observed = HGVSProtChange.fromStr("Trp24Cys")  # Missense
        self.assertEqual(observed, expected)
        expected = HGVSProtChange("Trp", 24, None, None, None, None, ["Cys"], True)
        observed = HGVSProtChange.fromStr("(Trp24Cys)")  # Missense
        self.assertEqual(observed, expected)
        expected = HGVSProtChange("Trp", 24, None, None, None, None, ["Ter"], False)
        observed = HGVSProtChange.fromStr("W24*")  # Nonsense
        self.assertEqual(observed, expected)
        observed = HGVSProtChange.fromStr("Trp24*")  # Nonsense
        self.assertEqual(observed, expected)
        observed = HGVSProtChange.fromStr("Trp24Ter")  # Nonsense
        self.assertEqual(observed, expected)
        expected = HGVSProtChange("Cys", 188, None, None, None, None, ["="], False)
        observed = HGVSProtChange.fromStr("C188=")  # No change
        self.assertEqual(observed, expected)
        observed = HGVSProtChange.fromStr("Cys188=")  # No change
        self.assertEqual(observed, expected)
        expected = HGVSProtChange("Gly", 56, None, None, None, None, ["Ala", "^", "Ser", "^", "Cys"], True)
        observed = HGVSProtChange.fromStr("(G56A^S^C)")  # Uncertain
        self.assertEqual(observed, expected)
        observed = HGVSProtChange.fromStr("(Gly56Ala^Ser^Cys)")  # Uncertain
        self.assertEqual(observed, expected)
        expected = HGVSProtChange("Trp", 24, None, None, None, None, ["=", "/", "Cys"], False)
        observed = HGVSProtChange.fromStr("W24=/C")  # Mosaic
        self.assertEqual(observed, expected)
        observed = HGVSProtChange.fromStr("Trp24=/Cys")  # Mosaic
        self.assertEqual(observed, expected)
        # Deletion
        expected = HGVSProtChange("Val", 7, None, None, None, "del", [], False)
        observed = HGVSProtChange.fromStr("V7del")
        self.assertEqual(observed, expected)
        observed = HGVSProtChange.fromStr("Val7del")
        self.assertEqual(observed, expected)
        expected = HGVSProtChange("Val", 7, None, None, None, "del", [], True)
        observed = HGVSProtChange.fromStr("(V7del)")
        self.assertEqual(observed, expected)
        observed = HGVSProtChange.fromStr("(Val7del)")
        self.assertEqual(observed, expected)
        expected = HGVSProtChange("Trp", 4, None, None, None, "del", [], False)
        observed = HGVSProtChange.fromStr("Trp4del")
        self.assertEqual(observed, expected)
        expected = HGVSProtChange("Lys", 23, "Val", 25, None, "del", [], False)
        observed = HGVSProtChange.fromStr("K23_V25del")
        self.assertEqual(observed, expected)
        observed = HGVSProtChange.fromStr("Lys23_Val25del")
        self.assertEqual(observed, expected)
        expected = HGVSProtChange("Pro", 458, "Gly", 460, None, "del", [], True)
        observed = HGVSProtChange.fromStr("(P458_G460del)")
        self.assertEqual(observed, expected)
        observed = HGVSProtChange.fromStr("(Pro458_Gly460del)")
        self.assertEqual(observed, expected)
        expected = HGVSProtChange("Gly", 2, "Met", 46, None, "del", [], False)
        observed = HGVSProtChange.fromStr("G2_M46del")
        self.assertEqual(observed, expected)
        observed = HGVSProtChange.fromStr("Gly2_Met46del")
        self.assertEqual(observed, expected)
        expected = HGVSProtChange("Trp", 26, None, None, None, None, ["Ter"], False)
        observed = HGVSProtChange.fromStr("W26*")
        self.assertEqual(observed, expected)
        observed = HGVSProtChange.fromStr("Trp26*")
        self.assertEqual(observed, expected)
        # observed = HGVSProtChange.fromStr("Val7=/del")
        # Duplication
        expected = HGVSProtChange("Ala", 3, None, None, None, "dup", [], False)
        observed = HGVSProtChange.fromStr("Ala3dup")
        self.assertEqual(observed, expected)
        observed = HGVSProtChange.fromStr("A3dup")
        self.assertEqual(observed, expected)
        expected = HGVSProtChange("Ala", 3, "Ser", 5, None, "dup", [], False)
        observed = HGVSProtChange.fromStr("A3_S5dup")
        self.assertEqual(observed, expected)
        observed = HGVSProtChange.fromStr("Ala3_Ser5dup")
        self.assertEqual(observed, expected)
        expected = HGVSProtChange("Ser", 6, None, None, None, "dup", [], False)
        observed = HGVSProtChange.fromStr("S6dup")
        self.assertEqual(observed, expected)
        observed = HGVSProtChange.fromStr("Ser6dup")
        self.assertEqual(observed, expected)
        # Insertion
        expected = HGVSProtChange("His", 4, "Gln", 5, None, "ins", ["Ala"], False)
        observed = HGVSProtChange.fromStr("H4_Q5insA")
        self.assertEqual(observed, expected)
        observed = HGVSProtChange.fromStr("His4_Gln5insAla")
        self.assertEqual(observed, expected)
        expected = HGVSProtChange("Lys", 2, "Gly", 3, None, "ins", ["Gln", "Ser", "Lys"], False)
        observed = HGVSProtChange.fromStr("K2_G3insQSK")
        self.assertEqual(observed, expected)
        observed = HGVSProtChange.fromStr("Lys2_Gly3insGlnSerLys")
        self.assertEqual(observed, expected)
        expected = HGVSProtChange("Met", 3, "His", 4, None, "ins", ["Gly", "Ter"], True)
        observed = HGVSProtChange.fromStr("(M3_H4insG*)")
        self.assertEqual(observed, expected)
        observed = HGVSProtChange.fromStr("(Met3_His4insGlyTer)")
        self.assertEqual(observed, expected)
        expected = HGVSProtChange("Arg", 78, "Gly", 79, None, "ins", ["23"], False)
        observed = HGVSProtChange.fromStr("R78_G79ins23")
        self.assertEqual(observed, expected)
        observed = HGVSProtChange.fromStr("Arg78_Gly79ins23")
        self.assertEqual(observed, expected)
        expected = HGVSProtChange("Gln", 746, "Lys", 747, None, "ins", ["Ter", "63"], False)
        observed = HGVSProtChange.fromStr("Q746_K747ins*63")
        self.assertEqual(observed, expected)
        observed = HGVSProtChange.fromStr("Gln746_Lys747ins*63")
        self.assertEqual(observed, expected)
        expected = HGVSProtChange("Ser", 332, "Ser", 333, None, "ins", ["(1)"], True)
        observed = HGVSProtChange.fromStr("(S332_S333ins(1))")
        self.assertEqual(observed, expected)
        observed = HGVSProtChange.fromStr("(Ser332_Ser333ins(1))")
        self.assertEqual(observed, expected)
        expected = HGVSProtChange("Ser", 332, "Ser", 333, None, "ins", ["Xaa"], True)
        observed = HGVSProtChange.fromStr("(S332_S333insX)")
        self.assertEqual(observed, expected)
        observed = HGVSProtChange.fromStr("(Ser332_Ser333insX)")
        self.assertEqual(observed, expected)
        expected = HGVSProtChange("Val", 582, "Asn", 583, None, "ins", ["(5)"], True)
        observed = HGVSProtChange.fromStr("(V582_N583ins(5))")
        self.assertEqual(observed, expected)
        observed = HGVSProtChange.fromStr("(Val582_Asn583ins(5))")
        self.assertEqual(observed, expected)
        expected = HGVSProtChange("Val", 582, "Asn", 583, None, "ins", ["Xaa", "Xaa", "Xaa", "Xaa", "Xaa"], True)
        observed = HGVSProtChange.fromStr("(Val582_Asn583insXXXXX)")
        self.assertEqual(observed, expected)
        observed = HGVSProtChange.fromStr("(Val582_Asn583insXaaXaaXaaXaaXaa)")
        self.assertEqual(observed, expected)
        # Frameshift
        expected = HGVSProtChange("Arg", 97, None, None, "Pro", "fs", ["Ter", "23"], False)
        observed = HGVSProtChange.fromStr("R97Pfs*23")
        self.assertEqual(observed, expected)
        observed = HGVSProtChange.fromStr("Arg97ProfsTer23")
        self.assertEqual(observed, expected)
        expected = HGVSProtChange("Arg", 97, None, None, None, "fs", [], False)
        observed = HGVSProtChange.fromStr("R97FS")
        self.assertEqual(observed, expected)
        observed = HGVSProtChange.fromStr("Arg97fs")
        self.assertEqual(observed, expected)
        expected = HGVSProtChange("Tyr", 4, None, None, None, None, ["Ter"], True)
        observed = HGVSProtChange.fromStr("(Y4*)")
        self.assertEqual(observed, expected)
        observed = HGVSProtChange.fromStr("(Tyr4*)")
        self.assertEqual(observed, expected)
        expected = HGVSProtChange("Ile", 327, None, None, "Arg", "fs", ["Ter", "?"], False)
        observed = HGVSProtChange.fromStr("I327Rfs*?")
        self.assertEqual(observed, expected)
        observed = HGVSProtChange.fromStr("Ile327Argfs*?")
        self.assertEqual(observed, expected)
        expected = HGVSProtChange("Gln", 151, None, None, "Thr", "fs", ["Ter", "9"], False)
        observed = HGVSProtChange.fromStr("Q151TFS*9")
        self.assertEqual(observed, expected)
        observed = HGVSProtChange.fromStr("Gln151Thrfs*9")
        self.assertEqual(observed, expected)
        # Extension
        expected = HGVSProtChange("Met", 1, None, None, None, "ext", ["-5"], False)
        observed = HGVSProtChange.fromStr("M1ext-5")
        self.assertEqual(observed, expected)
        observed = HGVSProtChange.fromStr("Met1ext-5")
        self.assertEqual(observed, expected)
        expected = HGVSProtChange("Ter", 110, None, None, "Gln", "ext", ["Ter", "17"], False)
        observed = HGVSProtChange.fromStr("*110Qext*17")
        self.assertEqual(observed, expected)
        observed = HGVSProtChange.fromStr("Ter110GlnextTer17")
        self.assertEqual(observed, expected)
        observed = HGVSProtChange.fromStr("*110Glnext*17")
        self.assertEqual(observed, expected)
        expected = HGVSProtChange("Ter", 315, None, None, "Tyr", "ext", ["Asn", "Lys", "Gly", "Thr", "Ter"], True)
        observed = HGVSProtChange.fromStr("(*315YextNKGT*)")
        self.assertEqual(observed, expected)
        observed = HGVSProtChange.fromStr("(Ter315TyrextAsnLysGlyThrTer)")
        self.assertEqual(observed, expected)
        expected = HGVSProtChange("Ter", 315, None, None, "Tyr", "ext", ["Asn", "Lys", "Gly", "Thr", "Ter"], False)
        observed = HGVSProtChange.fromStr("*315TyrextAsnLysGlyThr*")
        self.assertEqual(observed, expected)
        expected = HGVSProtChange("Ter", 327, None, None, "Arg", "ext", ["Ter", "?"], False)
        observed = HGVSProtChange.fromStr("*327Rext*?")
        self.assertEqual(observed, expected)
        observed = HGVSProtChange.fromStr("Ter327Argext*?")
        self.assertEqual(observed, expected)


########################################################################
#
# MAIN
#
########################################################################
if __name__ == "__main__":
    unittest.main()
