{% set version = "2.12.1" %}
{% set numpy_version = "=1.20.1" %}
{% set pysam_version = "=0.18.0" %}
{% set python_version = ">=3.5" %}
{% set requests_version = "=2.20.1" %}

package:
  name: anacore
  version: {{ version }}

source:
  git_url: https://github.com/bialimed/anacore
  git_rev: {{ version }}

build:
  number: 1
  script: ${PYTHON} setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python {{ python_version }}
    - setuptools
  run:
    - python {{ python_version }}
    - numpy {{ numpy_version }}
    - pysam {{ pysam_version }}
    - requests {{ requests_version }}

test:
  imports:
    - numpy
    - pysam
    - requests
    - anacore

about:
  summary: Anapath Core is a package containing libraries for managing standard file formats (BED, fasta, gff, gtf, MAF, newick, VCF, ...) and objects from NGS.
  license: GNU GPL v3
  home: https://github.com/bialimed/anacore
  doc_source_url: https://github.com/bialimed/anacore/blob/{{ version }}/README.md
