{% set project = load_file_data('../../pyproject.toml', from_recipe_dir=true).get("project") %}
{% set version = project.get("version") %}

package:
  name: {{ project["name"] }}
  version: {{ version }}

source:
  git_url: {{ project["urls"]["Repository"] }}
  git_rev: {{ version }}

build:
  number: 1
  script: ${PYTHON} -m pip install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python {{ project.get("requires-python", "") }}
    - setuptools
  run:
    - python {{ project.get("requires-python", "") }}
    {% for dep in project.get("dependencies") %}
    - {{ dep }}
    {% endfor %}

test:
  imports:
    {% for dep in project.get("dependencies") %}
    - {{ dep.split(" ")[0] }}
    {% endfor %}
    - anacore

about:
  summary: Anapath Core is a package containing libraries for managing standard file formats (BED, fasta, gff, gtf, MAF, newick, VCF, ...) and objects from NGS.
  license: {{ project["license"]["text"] }}
  home: {{ project["urls"]["Repository"] }}
  dev_url: project["urls"]["Repository"]
  doc_url: https://pypi.python.org/pypi/{{ project["name"] }}
  doc_source_url: {{ project["urls"]["Repository"] }}/blob/{{ version }}/README.md
